### ISSUE TITLE
inline image lineheight issue while reflow

### ISSUE THREAD

**Issue by ramtel2005** [ftlabs/ftcolumnflow#22]
I have set of paragraphs after third paragraph i have one img tag with "nowrap" class, all works fine while cf.flow(), when i changed font size and tried reflow() after image the lineheigth issue appears (half of the text in single line showing in endof column and remaining half showing in starting of next column)
![reflow_issue](https://f.cloud.github.com/assets/2009949/1085947/a4f8080e-15e8-11e3-9d58-6e34cf9ad4aa.png)

Note: with out inline image flow() and reflow() works fine with font size change.

**Comment by kushul** [comment]
@georgecrawford Im getting the same problem. how to fix this please?
