### ISSUE TITLE
Flowed content placement issue when entire 1st page is filled with fixed content

### ISSUE THREAD

**Issue by f4k1r** [ftlabs/ftcolumnflow#40]
I am using the horizontal scroll withe below values
var ft = new FTColumnflow('target', 'viewport', {
		//columnWidth:           120,
		columnCount:           4,
		standardiseLineHeight: true,
		pagePadding:           20,
		viewportWidth:         inWidth,
		viewportHeight:        inHeight-20,
		pageArrangement:       'horizontal',
		showGrid:              false,
		allowReflow:           true,
		minFixedPadding:       0.5
	});
The entire first page is filled with fixed content. In this case the flowing content is overwritten on the fixed content of first page.
Flow content overlapping on fixed content: http://s28.postimg.org/7mrmx73y5/flowcontent.png
Without flow content, only fixed content: http://s29.postimg.org/f64jukjqv/withoutfixedcontent.png
Is this a limitation or am I doing something wrong? I have searched through the docs as well.

**Comment by georgecrawford** [comment]
Hey,

Sorry it took me such a crazy long time to look at this. In your CodePen demo, the only problem is that the fixed elements are overlapping. The flowed content always sits nicely on page 2 for me. You already admit that you're pushing the limits of ColumnFlow by adding so much fixed content to a flexible viewport. But I don't think there's actually a bug here.
