### ISSUE TITLE
Spliting paragraphs between columns

### ISSUE THREAD

**Issue by rdadalski** [ftlabs/ftcolumnflow#42]
Is there any smart and fast way to implement spliting paragraphs between columns as you described here ? 

"Our first iteration looped through each word in the flowed text to determine whether or not it was within the bounds of the current column. When the first out-of-bounds word was found, the paragraph was split, and the second part moved over to a new column."

**Comment by georgecrawford** [comment]
Are you asking for this within Columnflow, or as a question independent of this library? The whole point here is that we *don't* do this kind of iterating through each word as it's very slow.

**Comment by rdadalski** [comment]
Yes, I'm asking for it within Columnflow, i need that to split the paragraph even if the performance is not that good, thought maybe you have a version with that implementation ?

**Comment by georgecrawford** [comment]
I don't understand the use-case. Columnflow works by not splitting the paragraph, and instead copying it to the next column and setting hidden offsets so it appears to be split. There's no version which uses text node splitting. If you can explain why you feel you need this, I might be able to help.

**Comment by jacekpl** [comment]
I work with @rdadalski, so I'll write here also:)
We use a legacy digital printing system and need to split a text word-by-word to fill up all the columns (without leaving empty space in column if one paragraph when it's long). To detect overflow we use scrollHeight property (which is really slow in IE). Our current solution is: https://gist.github.com/jacekpl/06b3ddae07e08e4accac

That's the use case:)

**Comment by georgecrawford** [comment]
Yep. I'm sorry, this is the exact problem Columnflow tries to escape, so I can't really help you!

**Comment by rdadalski** [comment]
Thanks for your effort :) Do you know any other solution we can check ?

**Comment by georgecrawford** [comment]
I don't, I'm afraid. Good luck!
