### ISSUE TITLE
Is it possible to have a new element other than fixed and flowed element?

### ISSUE THREAD

**Issue by charx0r** [ftlabs/ftcolumnflow#43]
I was wondering if we could have a new element which could be placed in a page irrespective of the col-span and anchoring. I have been experimenting with the library and getting great results. I was wondering if such a thing was possible then I could use shapes to wrap text around these fixed elements.
http://alistapart.com/article/css-shapes-101#figure12
http://alistapart.com/article/css-shapes-101#figure14
and create layouts which are closer to their print counterparts. CSS fragmentation and CSS Exclusions are still under drafts and shapes seem to be better way for now. 

This is what I have been working on: http://216.139.250.24/50-years/article/2015/04/The_Beginning

**Comment by georgecrawford** [comment]
Hi @f4k1r. I'm not quite sure what you mean by 'a new element which could be placed in a page irrespective of the col-span and anchoring'. What do you imagine the API would be, and what would be the result? Should it remain in the same page and position, or should it keep its inline position in the flow as the viewport is resized?

**Comment by f4k1r** [comment]
I was thinking an absolute element which would be placed using the absolute property with dimensions specified either in px or pc. Then have content flow around this. I was imaging where this div could span from the 50% of first column to the 50% of second column and the content wrapping around it.

I understand this will result in changing the way the positions are currently calculated. I was just wondering what your thoughts would be on this. 
Example layout: http://squeezecreative.com.au/wp-content/uploads/2010/12/print-summer-festival-guide-spread01.jpg The blurb text spans across 1.5 columns and the body content flowing in the remaining 0.5 column width.

**Comment by georgecrawford** [comment]
I'm sorry, this isn't a feature that ColumnFlow is ever likely to support.
